site_name: fmt-doc
site_url: https://example.com
repo_name: fmt-doc
repo_url: https://github.com/fmt-saas/fmt-doc
edit_uri: ""
docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
