site_name: fmt-doc
site_url: https://doc.fmt.yb.run
repo_name: fmt-doc
repo_url: https://github.com/fmt-saas/fmt-doc
edit_uri: ""
docs_dir: docs
nav:
  - 'Welcome': index.md
  - 'Modèles de données': modeles-de-donnees.md
  - 'Budget':
      - 'Appels de fonds': budget/appels-de-fonds.md
      - 'Suivi des appels': budget/suivi-des-appels.md
  - 'Comptabilité':
      - 'Balances comptables': comptabilite/balances-comptables.md
      - 'Clés de répartition': comptabilite/cles-de-repartition.md
      - 'Ecritures comptables': comptabilite/ecritures-comptables.md
      - 'Exercices comptables': comptabilite/exercices-comptables.md
      - 'Plan comptable': comptabilite/plan-comptable.md
      - 'Lettrage des écritures': comptabilite/lettrage.md
      - 'Encodage pièces comptables':
          - 'Factures d''achat': comptabilite/pieces-comptables/facture-achat.md
          - 'Décompte copropriétaires': comptabilite/pieces-comptables/decompte-coproprietaires.md
          - 'Appels de fonds': comptabilite/pieces-comptables/appel-de-fonds.md
  - 'Copropriété':
      - 'Création nouvelle Copropriété': copropriete/creation-nouvelle-copropriete.md
      - 'Configuration & paramétrage': copropriete/configuration.md
      - 'Fournisseur (`Supplier`)': copropriete/fournisseur-supplier.md
      - 'Gestion des charges communes': copropriete/gestion-des-charges-communes.md
      - 'Gestion des consommations (eau/gaz/élec)': copropriete/gestion-des-consommations-eau-gaz-elec.md
      - 'Propriétaires (`Ownership`)': copropriete/proprietaires-ownership.md
      - 'Mutations / Transferts de propriété': copropriete/mutations-transferts-de-propriete.md
      - 'Syndic / Agence (`ManagingAgent`)': copropriete/syndic-agence-managingagent.md
      - 'Comptes bancaires': copropriete/comptes-bancaires.md
  - 'Documents':
      - 'Aperçu': documents/documents.md
      - 'Organisation des documents':
          - 'Organisation des documents': documents/organisation-des-documents/organisation-des-documents.md
          - 'Types de documents': documents/organisation-des-documents/types-de-documents.md
          - 'Factures d''achat': documents/organisation-des-documents/purchase-invoice.md
          - 'Extraits bancaires': documents/organisation-des-documents/bank-statement.md
      - 'Document Processing':
          - 'Document Processing': documents/document-processing/document-processing.md
          - 'Document Analysis': documents/document-processing/document-analysis.md
          - 'Document Identification': documents/document-processing/document-identification.md
          - 'Document Validation': documents/document-processing/document-validation.md
          - 'Intégration comptable': documents/document-processing/document-integration.md
      - 'Email Digestor': documents/email-digestor/email-digestor.md
      - 'Signatures électroniques': documents/signatures-electroniques.md
  - 'Suivis':
      - 'Envois & Rappels': suivis/envois-et-rappels/envois-et-rappels.md
      - 'Réconciliation CODA': suivis/reconciliation-coda/reconciliation-coda.md
      - 'Suivis de dossiers': suivis/suivis-de-dossiers/suivis-de-dossiers.md
      - 'Suivis de paiement': suivis/suivis-de-paiement/suivis-de-paiement.md
  - 'Imports':
      - 'Imports': imports/imports.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
