site_name: fmt-doc
site_url: https://example.com
repo_name: fmt-doc
repo_url: https://github.com/fmt-saas/fmt-doc
edit_uri: ""
docs_dir: docs
nav:
  - 'Welcome': index.md
  - 'Budget':
      - 'Appels de fonds': budget/appels-de-fonds.md
      - 'Suivi des appels': budget/suivi-des-appels.md
  - 'Comptabilité':
      - 'Balances comptables': comptabilite/balances-comptables.md
      - 'Clés de répartition': comptabilite/cles-de-repartition.md
      - 'Ecritures comptables': comptabilite/ecritures-comptables.md
      - 'Exercices comptables': comptabilite/exercices-comptables.md
      - 'Plan comptable': comptabilite/plan-comptable.md
      - 'Factures d''achat': comptabilite/encodage-facture-achat/encodage-facture-achat.md
  - 'Copropriété':
      - 'Création d''une nouvelle Copropriété (import)': copropriete/creation-dune-nouvelle-copropriete-import.md
      - 'Fournisseur (`Supplier`)': copropriete/fournisseur-supplier.md
      - 'Gestion des charges communes': copropriete/gestion-des-charges-communes.md
      - 'Gestion des consommations (eau/gaz/élec)': copropriete/gestion-des-consommations-eau-gaz-elec.md
      - 'Propriétaires (`Ownership`)': copropriete/proprietaires-ownership.md
      - 'Syndic / Agence (`ManagingAgent`)': copropriete/syndic-agence-managingagent.md
  - 'Documents':
      - 'Organisation des documents': documents/organisation-des-documents.md
      - 'Document Processing': documents/document-processing.md
      - 'Email Digestor': documents/email-digestor.md
      - 'Encodage facture achat':
          - 'Découpage de la facture en lignes d’imputation (`InvoiceLine`)': documents/encodage-facture-achat/decoupage-de-la-facture-en-lignes-dimputation.md
          - 'Décompte copropriétaires ("répartition")': documents/encodage-facture-achat/decompte-coproprietaires.md
          - 'Ecritures de clôture de période': documents/encodage-facture-achat/ecritures-de-cloture-de-periode.md
          - 'Génération des écritures comptables': documents/encodage-facture-achat/generation-des-ecritures-comptables.md
          - 'Informations à renseigner': documents/encodage-facture-achat/informations-a-renseigner.md
          - 'Paiement': documents/encodage-facture-achat/paiement.md
          - 'Réconciliation CODA': documents/encodage-facture-achat/reconciliation-coda.md
          - 'workflow': documents/encodage-facture-achat/workflow.md
  - 'Suivis':
      - 'Envois & Rappels': suivis/envois-et-rappels.md
      - 'Réconciliation CODA': suivis/reconciliation-coda.md
      - 'Suivis de dossiers': suivis/suivis-de-dossiers.md
      - 'Suivis de paiement': suivis/suivis-de-paiement.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
